### ISSUE TITLE
excludeDevDependencies and symlinkOrCopy does not work well together

### ISSUE THREAD

**Issue by henrikbjorn** [prisma/serverless-plugin-typescript#154]
Using this plugin together with serverless framework made my package HUUUGE because it included all of the devDependencies etc.

While researching I found this issue https://github.com/serverless/serverless/issues/5396 and after more debugging I found the issue (on my system) https://github.com/serverless/serverless/issues/5396#issuecomment-508371082

Changing this function https://github.com/prisma/serverless-plugin-typescript/blob/master/src/index.ts#L227 to always do a copy and not use Symlinks excludes the devDependencies correctly.

**Comment by MennoTammens** [comment]
A fix for this issue was written a while ago by @jengjeng, but has a conflict with newer changes:
#101 

I've updated this PR in a new PR: #157

**Comment by JackCuthbert** [comment]
A fix has been merged for this issue in v1.1.8, I'll close this one for now. If it persists please open up a new one :smiley:

**Comment by SpencerBriereWEQ** [comment]
I believe this was this merge that broke us. Our node_modules is symlinked into our project directory. The use case is we have multiple sub-projects which share one set of dependencies. Rather than installing the same dependencies into 10 places, we use symlinks to tie node_modules into the sub-projects. Directly copying the node_modules breaks the symlink and our build fails, whereas <1.1.8 symlinks worked perfectly.
